### ISSUE TITLE
[Feature Request] Modded Ore Implimentation 

### ISSUE THREAD

**Issue by ArchOwlen** [Gitko01/BelowBedrockCaves#2]
I was planning on using the dimension alongside create to get some modded ores as well, but currently it only has vanilla ores

I may attempt to add Zinc as a test in the 1.20.1 branch if I have the time, but you may have an easier time doing so lol

**Comment by ChacePratt** [comment]
I’ve thought about adding modded ores, but I’m not 100% sure on how to do so because I haven’t done any research into it. I may look into it soon, as I have a good amount of free time coming up.

For each modded ore I’ll have to look into the source code of the mod to check how frequently the ore generates and have to make a texture.

Edit:
After looking through some of the popular tech mods, I got my work cut out for me here...
There are a LOT of ores... I may just start off with TechReborn and Powah! ores.

**Comment by ChacePratt** [comment]
Just released v1.1.0, and it includes ores from TechReborn and Powah! (Rearchitected)
I'm working on 1.20.2 support right now, and I may work on Create ores this weekend (or sooner if I have a bunch of free time this week)

**Comment by ChacePratt** [comment]
v1.2.0 - now with Create ores!
